spring.application.name=jug-feedback

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jugfeedback
spring.datasource.username=jugfeedback
spring.datasource.password=jugfeedback

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
