CREATE TABLE feedback_form (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    speaker_name    VARCHAR(255),
    topic           VARCHAR(255),
    status          VARCHAR(255) NOT NULL,
    public_token    VARCHAR(255) NOT NULL UNIQUE,
    created_at      TIMESTAMP NOT NULL
);

CREATE TABLE feedback_question (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id         BIGINT NOT NULL REFERENCES feedback_form(id),
    question_text   VARCHAR(255) NOT NULL,
    question_type   VARCHAR(255) NOT NULL,
    order_index     INTEGER NOT NULL
);

CREATE TABLE feedback_response (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id         BIGINT NOT NULL REFERENCES feedback_form(id),
    submitted_at    TIMESTAMP NOT NULL
);

CREATE TABLE feedback_answer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id     BIGINT NOT NULL REFERENCES feedback_response(id),
    question_id     BIGINT NOT NULL REFERENCES feedback_question(id),
    rating_value    INTEGER,
    text_value      VARCHAR(2000)
);

CREATE TABLE access_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    token           VARCHAR(255) NOT NULL UNIQUE,
    used            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL,
    expires_at      TIMESTAMP
);
