ALTER TABLE feedback_form ADD COLUMN owner_email VARCHAR(255);

CREATE TABLE form_share (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id         BIGINT NOT NULL REFERENCES feedback_form(id) ON DELETE CASCADE,
    shared_with_email VARCHAR(255) NOT NULL,
    UNIQUE (form_id, shared_with_email)
);
